# fly.toml app configuration file for reedstreams-edge-v2
app = 'reedstreams-edge-v2'
primary_region = 'dfw'

[build]

[env]
  CARGO_ENV = 'production'
  HOST = '0.0.0.0'
  HTTP_TIMEOUT = '60'
  PORT = '5000'
  REDIS_POOL_SIZE = '50'

# HTTP service for regular requests
[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  
  [http_service.concurrency]
    type = 'connections'
    hard_limit = 2500
    soft_limit = 2000

[[services]]
  protocol = 'tcp'
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 2500
    soft_limit = 2000

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 4
  memory_mb = 16384
